if filereadable(expand("~/.gvimrc_before"))
    source ~/.gvimrc_before
endif

let oldcwd=getcwd()
cd $ROOT/vim
source $ROOT/vim/gvimrc
cd `=oldcwd`

if filereadable(expand("~/.gvimrc_after"))
    source ~/.gvimrc_after
endif
